// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHkAQr0seUDzMNR-Kz1VyF8VKMdpkp7Jg',
    appId: '1:888324707041:android:2e8cc988d2f7d3e915dda0',
    messagingSenderId: '888324707041',
    projectId: 'crave-1bf8a',
    storageBucket: 'crave-1bf8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtv4ftRW9YxJMtkAAJ61eRcS1NJDJESIY',
    appId: '1:888324707041:ios:428637a160e4d28d15dda0',
    messagingSenderId: '888324707041',
    projectId: 'crave-1bf8a',
    storageBucket: 'crave-1bf8a.firebasestorage.app',
    iosBundleId: 'com.example.version2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyDlyVncI_HzARvLuyUuOn_tvTp0xowE8',
    appId: '1:888324707041:web:656b96f9853940ef15dda0',
    messagingSenderId: '888324707041',
    projectId: 'crave-1bf8a',
    authDomain: 'crave-1bf8a.firebaseapp.com',
    storageBucket: 'crave-1bf8a.firebasestorage.app',
    measurementId: 'G-N5K48XKHD8',
  );

}